name: Ls åss
description: Cybersecurity Research
meta_description: "Cybersecurity Research"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ''
domain_name: 'https://lsass.io/blog/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://lsass.io'
author:         ''
